### ISSUE TITLE
Clamping does not work correctly in SSE code if wrong color space is used

### ISSUE THREAD

**Issue by mika-fischer** [descampsa/yuv2rgb#12]
If I have data with format `YCBCR_JPEG`, but call the yuv -> rgb functions with `YCBCR_601` instead, I would expect some values to get clipped.

That also happens correctly for the `_std` functions, but not for the `_sse` and `_sseu` functions. There, the pixel values that get > 255 somehow overflow and turn out black...

**Comment by descampsa** [comment]
You are right, but I am not sure how I can fix this without losing too much speed. Added to the todo list ;-)

**Comment by descampsa** [comment]
Should be fixed in e805bf2ef80d3cc4c5bc84270fd77cbaba3173ef
Sorry for the slight delay ;-)
