### ISSUE TITLE
do you have plan for `rgb24_to_yuv420p` ?

### ISSUE THREAD

**Issue by LuoZijun** [descampsa/yuv2rgb#2]
hi, do you have any plan for `rgb24_to_yuv420p` ? 👍

**Comment by descampsa** [comment]
Yes, there was a plan for it originally. 
I kind of forgot about it, but i will have a look when i have some free time.

**Comment by LuoZijun** [comment]
that's great, and when you finished, may i translate to my project https://github.com/OpenAnsible ?

**Comment by descampsa** [comment]
I have finally had the time to finish and properly test the rgb24_to_yuv420 functions , they should be ok now, feel free to test them.
You are very welcome to use my code in any way you want, as long as you follow the BSD license.
Out of curiosity, what is your "OpenAnsible" project? I could not find any  description of it  (not in a language i speak, at least ;-) )

**Comment by LuoZijun** [comment]
Oh, `OpenAnsible ` is an LiveCast project. Like Twitch TV .
